### ISSUE TITLE
Error occured wtih aschange skill.

### ISSUE THREAD

**Issue by miglas** [BerndiVader/mmArmorStandAnimator#2]
I made test2.anim skill for attack motion.
test2.anim works fine on using initas skill, but when I use aschange, it spit error (file not found)

java.io.FileNotFoundException: plugins/MythicMobs\Anims/test2.anim
[, 19. 6 2018 15:38:46 JST WARN]     at java.io.FileInputStream.open0(Native Method)
[, 19. 6 2018 15:38:46 JST WARN]     at java.io.FileInputStream.open(FileInputStream.java:195)
[, 19. 6 2018 15:38:46 JST WARN]     at java.io.FileInputStream.<init>(FileInputStream.java:138)
[, 19. 6 2018 15:38:46 JST WARN]     at java.io.FileReader.<init>(FileReader.java:72)
[, 19. 6 2018 15:38:46 JST WARN]     at com.gmail.berndivader.animatorstands.ArmorStandAnimator.loadFrames(ArmorStandAnimator.java:266)
[, 19. 6 2018 15:38:46 JST WARN]     at com.gmail.berndivader.animatorstands.ArmorStandAnimator.changeAnim(ArmorStandAnimator.java:251)
[, 19. 6 2018 15:38:46 JST WARN]     at com.gmail.berndivader.animatorstands.ArmorStandUtils.changeAnimation(ArmorStandUtils.java:50)
[, 19. 6 2018 15:38:46 JST WARN]     at com.gmail.berndivader.animatorstands.mechanics.ArmorStandChangeAnimMechanic.castAtEntity(ArmorStandChangeAnimMechanic.java:31)
[, 19. 6 2018 15:38:46 JST WARN]     at io.lumine.xikage.mythicmobs.skills.SkillMechanic.lambda$executeTargetedEntitySkill$0(SkillMechanic.java:408)
[, 19. 6 2018 15:38:46 JST WARN]     at java.lang.Iterable.forEach(Iterable.java:75)
[, 19. 6 2018 15:38:46 JST WARN]     at io.lumine.xikage.mythicmobs.skills.SkillMechanic.executeTargetedEntitySkill(SkillMechanic.java:404)
[, 19. 6 2018 15:38:46 JST WARN]     at io.lumine.xikage.mythicmobs.skills.SkillMechanic$3.run(SkillMechanic.java:361)
[, 19. 6 2018 15:38:46 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[, 19. 6 2018 15:38:46 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[, 19. 6 2018 15:38:46 JST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[, 19. 6 2018 15:38:46 JST WARN]     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[, 19. 6 2018 15:38:46 JST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[, 19. 6 2018 15:38:46 JST WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[, 19. 6 2018 15:38:46 JST WARN]     at java.lang.Thread.run(Thread.java:748)

**Comment by miglas** [comment]
I think linux cant use \
plugins/MythicMobs\ <= this 
can you change?
